// Code generated by "stringer -type=TokenType"; DO NOT EDIT.

package token

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TOKEN_PRI_TYPE-1]
	_ = x[TOKEN_VAR_NAME-2]
	_ = x[TOKEN_OP-3]
	_ = x[TOKEN_SEMI-4]
	_ = x[TOKEN_LEFT_PARENTHESE-5]
	_ = x[TOKEN_RIGHT_PARENTHESE-6]
	_ = x[TOKEN_NUMBER-7]
	_ = x[TOKEN_EOF-8]
	_ = x[TOKEN_COMMMA-9]
}

const _TokenType_name = "TOKEN_PRI_TYPETOKEN_VAR_NAMETOKEN_OPTOKEN_SEMITOKEN_LEFT_PARENTHESETOKEN_RIGHT_PARENTHESETOKEN_NUMBERTOKEN_EOFTOKEN_COMMMA"

var _TokenType_index = [...]uint8{0, 14, 28, 36, 46, 67, 89, 101, 110, 122}

func (i TokenType) String() string {
	i -= 1
	if i >= TokenType(len(_TokenType_index)-1) {
		return "TokenType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
